language: python

python:
  - "3.6"
  
install: 
  - pip install -r requirements.txt

before_script:
  - export FLASK_APP= 'run.py'
  - export FLASK_DEBUG=1
  - export FLASK_ENV= development

script: 'true'
