language: python

python:
  - "3.6"
  
install: 
  - pip install -r requirements.txt

env:
  - export FLASK_APP= 'run.py'
  - export FLASK_DEBUG=1
  - export FLASK_ENV= development

script:
  - py.test --cov=tests -v

after_success:
  - coveralls
