language: python

python:
  - "3.5"
  - "3.6"
  
install: 
  - pip install -r requirement.txt

before_script:
  - export FLASK_APP= run.py
  - export FLASK_DEBUG=1
  - export FLASK_ENV= development

script: 'true'
