language: python

python:
  - "3.6"
  
install: 
  - pip install -r requirements.txt
  - pip install coveralls

env:
  - export FLASK_APP= 'run.py'
  - export FLASK_DEBUG=1
  - export FLASK_ENV= development

script:
  - pytest -v tests/
  - - coverage run --source=app -m pytest && coverage report

after_success:
  - coveralls
